import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import { buildMetaAdsLibraryUrl,normalizeMetaAd,parseManualImport } from "../packages/connectors/src/meta-ads.ts";import { Phase2MemoryStore,scoreOpportunity } from "../packages/domain/src/phase2.ts";
const fixture=JSON.parse(fs.readFileSync("fixtures/meta-ads/manual-import.sample.json","utf8"));
test("Phase 2 fixture normalizer yields stable source identity",()=>{const first=parseManualImport(fixture,"2026-07-19T01:00:00Z");const second=parseManualImport(fixture,"2026-07-19T02:00:00Z");assert.equal(first[0].canonicalKey,second[0].canonicalKey);assert.equal(first[0].contentFingerprint,second[0].contentFingerprint)});
test("same fixture twice creates one canonical ad and two observations",()=>{const store=new Phase2MemoryStore();store.run("sneakers",parseManualImport(fixture,"2026-07-19T01:00:00Z"));store.run("sneakers",parseManualImport(fixture,"2026-07-19T02:00:00Z"));assert.equal(store.ads.size,2);assert.equal(store.ads.get("ad-1")?.observations.length,2);assert.equal(store.scans.length,2)});
test("failed scan preserves last known good ads",()=>{const store=new Phase2MemoryStore();store.run("sneakers",parseManualImport(fixture));const keys=[...store.ads.keys()];const failed=store.run("sneakers",[],"PLAYWRIGHT_BROWSER_NOT_CONFIGURED");assert.equal(failed.status,"failed");assert.deepEqual([...store.ads.keys()],keys)});
test("partial scan keeps normalized results and reports partial",()=>{const store=new Phase2MemoryStore();const scan=store.run("sneakers",[parseManualImport(fixture)[0]],"SOURCE_TIMEOUT");assert.equal(scan.status,"partial");assert.equal(store.ads.size,1)});
test("manual extension envelope maps legacy fields",()=>{const [ad]=parseManualImport({duplicateAds:[{adId:"991",advertiserName:"Legacy Store",adText:"Text evidence",adHeadline:"Offer",ctaText:"Shop",platforms:"Facebook, Instagram"}]});assert.equal(ad.canonicalKey,"meta_ads_library:991");assert.deepEqual(ad.observation.platforms,["Facebook","Instagram"])});
test("fingerprint fallback ignores whitespace differences",()=>{const a=normalizeMetaAd({advertiserName:"Store",body:"Daily shoes",headline:"Offer"});const b=normalizeMetaAd({advertiserName:" Store ",body:"Daily   shoes",headline:"Offer"});assert.equal(a.canonicalKey,b.canonicalKey)});
test("selected evidence creates scored opportunity and next action",()=>{const store=new Phase2MemoryStore();store.run("sneakers",parseManualImport(fixture));const opportunity=store.createOpportunity({name:"Sneakers test",adIds:["ad-1","ad-2"],reason:"multi ad evidence",nextAction:"Validate supplier"});assert.equal(opportunity.status,"watching");assert.equal(opportunity.nextAction,"Validate supplier");assert.ok(opportunity.score>0);assert.ok(opportunity.confidence>0)});
test("score confidence increases with evidence completeness",()=>{const store=new Phase2MemoryStore();store.run("x",parseManualImport(fixture));const ads=[...store.ads.values()];assert.ok(scoreOpportunity(ads).confidence>scoreOpportunity([ads[0]]).confidence)});
test("Phase 2 migration creates canonical and decision tables",()=>{const sql=fs.readFileSync("packages/db/prisma/migrations/20260719010000_phase2_meta_ads_opportunities/migration.sql","utf8");for(const table of ["Advertiser","CompetitorAd","AdScan","AdObservation","Opportunity","OpportunityEvidence","DecisionLog"])assert.ok(sql.includes(`CREATE TABLE "${table}"`))});
test("Playwright execution stays in worker boundary",()=>{const web=fs.readFileSync("apps/web/lib/phase2/service.ts","utf8");const worker=fs.readFileSync("apps/worker/src/meta-ads-worker.ts","utf8");assert.ok(!web.includes("scanMetaAdsLibrary("));assert.ok(worker.includes("scanMetaAdsLibrary("));assert.ok(web.includes("meta_ads.playwright_scan"))});

test("worker deduplicates duplicate DOM nodes before observations",()=>{const worker=fs.readFileSync("apps/worker/src/meta-ads-worker.ts","utf8");assert.ok(worker.includes("new Map(normalized.map(row => [row.canonicalKey, row]))"))});

test("progress modal polls real scan status and worker recovers stale jobs",()=>{const ui=fs.readFileSync("apps/web/components/meta-ads-inbox.tsx","utf8");const worker=fs.readFileSync("apps/worker/src/meta-ads-worker.ts","utf8");assert.ok(ui.includes("/api/meta-ads/scans/${scanId}"));assert.ok(ui.includes("role=\"dialog\""));assert.ok(worker.includes("WORKER_STALE_TIMEOUT"));assert.ok(worker.includes("PLAYWRIGHT_SCAN_TIMEOUT"))});

test("Meta Ads URL uses the same explicit filters and ordering as the public results page",()=>{const url=new URL(buildMetaAdsLibraryUrl("Gamis"));assert.equal(url.hostname,"www.facebook.com");assert.equal(url.pathname,"/ads/library/");assert.equal(url.searchParams.get("country"),"ID");assert.equal(url.searchParams.get("ad_type"),"all");assert.equal(url.searchParams.get("active_status"),"active");assert.equal(url.searchParams.get("is_targeted_country"),"false");assert.equal(url.searchParams.get("media_type"),"all");assert.equal(url.searchParams.get("q"),"Gamis");assert.equal(url.searchParams.get("search_type"),"keyword_unordered");assert.equal(url.searchParams.get("sort_data[mode]"),"total_impressions");assert.equal(url.searchParams.get("sort_data[direction]"),"desc")});
test("Meta Ads URL accepts a selected region",()=>{const url=new URL(buildMetaAdsLibraryUrl("shoes","MY"));assert.equal(url.searchParams.get("country"),"MY")});
test("scan UI exposes region and fixed All ads category",()=>{const ui=fs.readFileSync("apps/web/components/meta-ads-inbox.tsx","utf8");assert.ok(ui.includes(">Region<"));assert.ok(ui.includes("<option value=\"all\">All ads</option>"));assert.ok(ui.includes("country, targetCount, method, payload"))});
test("AdScan migration persists country with Indonesia default",()=>{const sql=fs.readFileSync("packages/db/prisma/migrations/20260720000000_phase2_scan_country/migration.sql","utf8");assert.ok(sql.includes('ADD COLUMN "country"'));assert.ok(sql.includes("DEFAULT 'ID'"))});
test("incremental Playwright collector waits for lazy-loaded IDs and reports batches",()=>{const connector=fs.readFileSync("packages/connectors/src/meta-ads.ts","utf8");assert.ok(connector.includes("document.scrollingElement?.scrollHeight"));assert.ok(connector.includes("waitForNewMetaAdId"));assert.ok(connector.includes("nextNudgeAt"));assert.ok(connector.includes("options.resultWaitMs"));assert.ok(connector.includes("options.stableRounds ?? 5"));assert.ok(connector.includes("options.onProgress?."));assert.ok(connector.includes("options.shouldStop?."));assert.ok(connector.includes('stopReason = "user_requested"'))});
test("worker persists each batch and summarizes after a stop request",()=>{const worker=fs.readFileSync("apps/worker/src/meta-ads-worker.ts","utf8");assert.ok(worker.includes("persistBatch("));assert.ok(worker.includes("adObservation.upsert"));assert.ok(worker.includes('status: "summarizing"'));assert.ok(worker.includes("summarizeScan("))});
test("scan modal exposes target, live count, stop reason, and Stop & rangkum",()=>{const ui=fs.readFileSync("apps/web/components/meta-ads-inbox.tsx","utf8");const service=fs.readFileSync("apps/web/lib/phase2/service.ts","utf8");assert.ok(ui.includes(">Target iklan<"));assert.ok(ui.includes("live-scan-counter"));assert.ok(ui.includes("scanStopReasonLabel"));assert.ok(ui.includes("Alasan berhenti"));assert.ok(ui.includes("Stop & rangkum"));assert.ok(ui.includes("/stop"));assert.ok(service.includes("stopReason"))});
test("incremental scan migration adds progress and summary fields",()=>{const sql=fs.readFileSync("packages/db/prisma/migrations/20260720010000_phase2_incremental_scan/migration.sql","utf8");for(const field of ["targetCount","discoveredCount","scrollCount","stopRequestedAt","duplicateGroupCount","advertiserCount"])assert.ok(sql.includes(`"${field}"`))});
